baseURL = "http://silenceisthecrime.com/"
languageCode = "en-us"
title = "Gabriel's Blog"
theme = "hello-friend-ng" #theme by https://atlialp.com/
baseurl = "/"

# googleAnalytics = ""

[author]
    name = "Gabriel Ting"

[taxonomies]
  tag = "tags"
  category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Gabriel Ting"
  keywords = "homepage, blog, computer, science, development, programming"
  images = [""]

  homeSubtitle = "Sophomore CS Student at Vanderbilt University"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:gt@gabrielting.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/gfting/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/gfting/"

[languages]
  [languages.en]
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "/root"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"