baseURL = "https://silenceisthecrime.com/"
title = "Gabriel Ting"

theme = "hello-friend-ng" #theme by https://atlialp.com/

DefaultContentLanguage = "en"

# googleAnalytics = ""

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "gfting"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag = "tags"
  category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Gabriel Ting"
  keywords = "homepage, blog, computer, science, development, programming"
  images = [""]

  homeSubtitle = "Sophomore CS Student at Vanderbilt University"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/writing`)
  contentTypeName = "writing"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:gt@gabrielting.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/gfting/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/gfting/"
  
  [params.logo]
    logoText = "/root"
    logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

#[languages] 
  #[languages.en]
    #subtitle = "Gabriel Ting" : this is for adding a subtitle in tabs
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "resume"
    name       = "Résumé"
    url        = "/resume"
  [[menu.main]]
    identifier = "writing"
    name       = "Writing"
    url        = "/writing"